#! /bin/bash
#

PRG=wfm_test.bin
if [ -n "$1" ]; then
       PRG=$1
       shift
fi

if [ ! -x ~ma/bin/sy2l.tcl ]; then
	exec ./$PRG
fi

LPIPE=Y2LOGFILE
test -p "$LPIPE" || {
        test -e "$LPIPE" && { echo "No pipe '$LPIPE' exists"; exit 1; }
        mkfifo $LPIPE
}
if ! fuser $LPIPE >/dev/null; then
	#echo
        ~ma/bin/sy2l.tcl $LPIPE &
fi

make -C ../../src || exit 1
make $PRG         || exit 1

export Y2SLOG_FILE=-
#export Y2SLOG_DEBUG=
export Y2DEBUG=1
./$PRG "$@" 2> $LPIPE
